version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
       - postgres:/data/postgres
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"

volumes:
    postgres:
    redis: