version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
       - postgres:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"
  
  back-end:
    build: 
      context: ./back-end-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT:  ${REDIS_PORT}

  front-end:
    build: 
      context: ./front-end
    restart: always
    ports:
      - "3003:80"
    depends_on:
      - db
      - redis
      - back-end
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}

volumes:
    postgres:
    redis:
