FROM node:18 as base

RUN npm install -g pm2

FROM base as builder

# Create app directory
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./

RUN npm install
RUN npx playwright install chromium
RUN npx playwright install-deps

RUN npm install

COPY --chown=node:node . .

RUN npm run build
RUN npm install puppeteer

EXPOSE 3000

CMD npm run migration:run && pm2-runtime start pm2-config.yml
