FROM node:18 as base

RUN apt update && apt install -y \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libexpat1 \
    libgbm1 \
    libglib2.0-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libudev1 \
    libuuid1 \
    libx11-6 \
    libx11-xcb1 \
    libxcb-dri3-0 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxkbcommon0 \
    libxrandr2 \
    libxrender1 \
    libxshmfence1 \
    libxss1 \
    libxtst6 && \
    rm -rf /var/lib/apt/lists/*


RUN npm install -g pm2

FROM base as builder

# Create app directory
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN npm run build
RUN npm install puppeteer

EXPOSE 3000

CMD npm run migration:run && pm2-runtime start pm2-config.yml
